VMS-14410: postinst: Enchance error catching during obtaining Server PID/UID
<==== Mercurial data ====>
Branch: vms_4.0_server

diff --git a/vms/distribution/deb/mediaserver/deb_files.in/debian/postinst b/vms/distribution/deb/mediaserver/deb_files.in/debian/postinst
--- a/vms/distribution/deb/mediaserver/deb_files.in/debian/postinst
+++ b/vms/distribution/deb/mediaserver/deb_files.in/debian/postinst
@@ -299,9 +299,28 @@ fi
 
 systemctl enable $COMPANY_NAME-mediaserver || exit $?
 
+# [out] SERVER_PID
+# [out] SERVER_UID
+getServerProcessInfo()
+{
+    if ! SERVER_PID=$(pidof mediaserver-bin)
+    then
+        return 1
+    fi
+
+    # Get UID of proccess with $SERVER_PID.
+    if ! SERVER_UID=$(ps -h -eo uid -q $SERVER_PID | grep -o '[[:digit:]]\+')
+    then
+        return 1
+    fi
+
+    return 0
+}
+
 startServer()
 {
     local SERVER_PID
+    local SERVER_UID
 
     if [[ $WITH_ROOT_TOOL == 'true' ]]
     then
@@ -311,13 +330,12 @@ startServer()
     systemctl start $COMPANY_NAME-mediaserver
 
     sleep 1
-    if ! SERVER_PID=$(pidof mediaserver-bin)
+    if ! getServerProcessInfo
     then
-        echo "ERROR: Server process not found though 'systemd ... start' reported success." >&2
+        echo "ERROR: Server process not found \
+            despite 'systemd ... start' returned zero exit status." >&2
         exit 1
     fi
-
-    local -ci SERVER_UID=$(ps -h -eo uid -q $SERVER_PID) #< Get UID of proccess with $SERVER_PID.
 
     echo "Started service with PID=$SERVER_PID, UID=$SERVER_UID."
 }
