Fixed dpkg error with failed 'service root-tool start'
<==== Mercurial data ====>
Branch: x_vms_docker_compatibility

diff --git a/vms/distribution/deb/mediaserver/deb_files.in/debian/postinst b/vms/distribution/deb/mediaserver/deb_files.in/debian/postinst
--- a/vms/distribution/deb/mediaserver/deb_files.in/debian/postinst
+++ b/vms/distribution/deb/mediaserver/deb_files.in/debian/postinst
@@ -30,15 +30,6 @@ EC_CFG_HELPER="$BIN_DIR/config_helper.py $EC_CONFIG_FILE"
 DBSYNC="$BASE_DIR/share/dbsync-2.2/bin/dbsync"
 CERTGEN="$BASE_DIR/share/dbsync-2.2/bin/certgen"
 
-# This is necessary because changed configuration options should take effect
-# immediately.
-
-if [ $(which systemctl) ]; then
-    systemctl stop $COMPANY_NAME-mediaserver || true
-else
-    service $COMPANY_NAME-mediaserver stop || true
-fi
-
 # Default MS parameters
 PORT_DEFAULT="7001"
 TRANSPORT_DEAULT="auto"
@@ -171,6 +162,15 @@ function display_complete_setup_hint {
     fi
 }
 
+# This is necessary because changed configuration options should take effect
+# immediately.
+
+if [ $(which systemctl) ]; then
+    systemctl stop $COMPANY_NAME-mediaserver || true
+else
+    service $COMPANY_NAME-mediaserver stop || true
+fi
+
 case "$1" in
     configure)
         ECS_GUID="$($EC_CFG_HELPER ecsGuid)"
@@ -295,7 +295,9 @@ if [ $(which systemctl) ]; then
     systemctl enable $COMPANY_NAME-mediaserver || exit $?
 fi
 
-service $COMPANY_NAME-root-tool start;
+# We have already added root tool to autolaunch, so no need to fail dpkg completely if 'service' command can not start right now
+service $COMPANY_NAME-root-tool start || true
+
 if service $COMPANY_NAME-mediaserver start; then
     sleep 1
     echo Start service $(ps aux | grep "mediaserver-bin -e" | grep -v grep)
