create_mediaserver_tar script now checks tmp dir permissions
<==== Mercurial data ====>
Branch: master

diff --git a/edge_firmware/isd/create_mediaserver_tar b/edge_firmware/isd/create_mediaserver_tar
--- a/edge_firmware/isd/create_mediaserver_tar
+++ b/edge_firmware/isd/create_mediaserver_tar
@@ -16,7 +16,7 @@ function get_var()
     if [[ "$1" == "QN_CUSTOMIZATION_NAME" && "$h" == "default" ]]; then
         h=networkoptix
     fi
-    echo "$h"
+    echo "$h" | head -n 1
 }
 
 
@@ -34,6 +34,13 @@ BOX_NAME=$(get_var "QN_ARM_BOX")
 PACKAGE_NAME=$CUSTOMIZATION-$PRODUCT_NAME-$MODULE_NAME-$VERSION-$BOX_NAME.tar.gz
 
 BUILD_DIR=/tmp/hdw_isd_build.tmp
+
+touch "/tmp" 2>/dev/null 1>&2
+if [ "$?" != 0 ]; then
+    echo "Failure: Cannot write to /tmp directory. Cannot continue. Exiting..."
+    exit 1
+fi
+
 PREFIX_DIR=/usr/local/apps/$CUSTOMIZATION
 
 BUILD_OUTPUT_DIR=$SRC_DIR/build_environment/target-$BOX_NAME
