NX1-42: Fixed removing Lite Client from Nx1
<==== Mercurial data ====>
Branch: vms_3.2_release

diff --git a/edge_firmware/rpi/maven/bpi/opt/networkoptix/mediaserver/var/scripts/start_lite_client b/edge_firmware/rpi/maven/bpi/opt/networkoptix/mediaserver/var/scripts/start_lite_client
--- a/edge_firmware/rpi/maven/bpi/opt/networkoptix/mediaserver/var/scripts/start_lite_client
+++ b/edge_firmware/rpi/maven/bpi/opt/networkoptix/mediaserver/var/scripts/start_lite_client
@@ -46,6 +46,12 @@ closeInheritedFileDescriptors()
 main()
 {
     logArgs "$@"
+
+    if [ ! -d "$LITE_CLIENT_DIR" ]; then
+        echo "[$0]: ERROR: Lite Client directory does not exist"
+        exit 1
+    fi
+
     closeInheritedFileDescriptors
 
     export LESS_TERMCAP_ue=""
