MOBILE-246: Control Nx1 HDMI monitor (TV) power state. Reject
<==== Mercurial data ====>
Branch: release_3.0

diff --git a/edge_firmware/rpi/maven/bpi/opt/networkoptix/mediaserver/var/scripts/start_lite_client b/edge_firmware/rpi/maven/bpi/opt/networkoptix/mediaserver/var/scripts/start_lite_client
--- a/edge_firmware/rpi/maven/bpi/opt/networkoptix/mediaserver/var/scripts/start_lite_client
+++ b/edge_firmware/rpi/maven/bpi/opt/networkoptix/mediaserver/var/scripts/start_lite_client
@@ -20,9 +20,10 @@ BIN_NAME=mobile_client
 
 killall gpm
 
-if ! (get-edid | parse-edid | grep -Fxq 'Section "Monitor"') 2>/dev/null; then
-    AUTO_LOGIN_MODE="--auto-login=disabled"
-fi
+# Failed to determine EDID on some TVs, so commenting this section
+#if ! (get-edid | parse-edid | grep -Fxq 'Section "Monitor"') 2>/dev/null; then
+#    AUTO_LOGIN_MODE="--auto-login=disabled"
+#fi
 
 LD_PRELOAD="/opt/$CUSTOMIZATION/lib/ldpreloadhook.so"
 /opt/$CUSTOMIZATION/lite_client/bin/mobile_client $* $AUTO_LOGIN_MODE >>/opt/$CUSTOMIZATION/mediaserver/var/log/mobile_client.log
